//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34003
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cuadernos_1934.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cuadernos_1934.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 0003;BDEPESM1XXX
        ///0004;BANDESSSXXX
        ///0009;FICDESM1XXX
        ///0019;DEUTESBBXXX
        ///0024;BALEES22XXX
        ///0030;ESPCESMMXXX
        ///0031;ETCHES2GXXX
        ///0036;SABNESMMXXX
        ///0042;BGUIES22XXX
        ///0046;GALEES2GXXX
        ///0049;BSCHESMMXXX
        ///0057;BVADESMMXXX
        ///0058;BNPAESMMXXX
        ///0059;MADRESMMXXX
        ///0061;BMARES2MXXX
        ///0065;BARCESMMXXX
        ///0072;PSTRESMMXXX
        ///0073;OPENESMMXXX
        ///0075;POPUESMMXXX
        ///0078;BAPUES22XXX
        ///0081;BSABESBBXXX
        ///0082;CASTES2SXXX
        ///0083;RENBESMMXXX
        ///0086;NORTESMMXXX
        ///0093;VALEESVVXXX
        ///0094;BVALESMMXXX
        ///0095;VASCES2PXXX
        ///0097;GALIES2VXXX
        ///0099;AHC [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string bic_sepa42 {
            get {
                return ResourceManager.GetString("bic_sepa42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Logo_Alvores {
            get {
                object obj = ResourceManager.GetObject("Logo_Alvores", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
